version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agro_scale_postgres
    restart: always
    environment:
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: agro_password
      POSTGRES_DB: agro_scale_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
